services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
      - TOKEN=${TOKEN}
    platform: linux/amd64